# ENSF 519.01 Applied Data Science 
**Assignment 1** - 100 marks

**Due:** October 4th, 04.00 pm.


**IMPORTANT NOTE: each task must be implemented as asked, even if there are other easier or better solutions.**

**How to deliver:**
Edit this file and write your solutions in sections specified with `# Your solution`. Test your code and when you were done, submit this notebook as an `.ipynb` file to D2L dropbox. 



## Problem 1 - The Zipf mystery (50 points)

In this problem, we'd like to read the text from a book and perform some simple statistical analysis on the word counts. We have provided you with the actual text from [Lost On The Moon or, In Quest of the Field of Diamonds](https://www.goodreads.com/book/show/8636132-lost-on-the-moon-or-in-quest-of-the-field-of-diamonds) book in a file named 'the book.txt'. The file is cleaned up and only contains alphanumeric characters, i.e. no punctuation, quotation marks, etc.

Read the file and break it down to its words. (5 points)

In [2]:
import os
import re

def read_and_tokenize(file_name):
    book_text = open(file_name, "r").read()
    book_words = re.findall("\s*(\S+)s*", book_text)
    return book_words
    
words = read_and_tokenize('the book.txt')
words[1101:1111] # Expected: ['the', 'latter', 'picked', 'it', 'up', 'gazed', 'at', 'it', 'first', 'from']

['the', 'latter', 'picked', 'it', 'up', 'gazed', 'at', 'it', 'first', 'from']

Using a sorted list of unique words in the book. Store the list in a variable called `V`. Also complete the `get_word_index` function below that gets a word and finds its index within `V`. (5 points)

In [3]:
# Your solution goes here
V = sorted(set(words))
def get_word_index(word):
    return V.index(word)

get_word_index('about')  # Expected: 9

9

Using no loops, and by only using `map` and `filter` built-in python functions traverse through the `V` (vocabulary) list above to find:

* `long_words`: The list of words that have 10 letters or more 
* `no_vowels`: A list of all words but with vowels (aoeiu) removed. You can nest `map` and `filter` calls to iterate through the characters of the words.

(5+5 points)

In [4]:
# Your solution here
def check_vowel(char):
    print(char)
    if char in ['a','e', 'i', 'o', 'u']:
        return "h"
    
long_words = list(filter(lambda word: len(word) >= 10, V))
#print(long_words)
no_vowels = list(map(lambda word: re.sub("[aeiou]", "", word), V))
#print(no_vowels)

Create a numpy array of size `|V|` that only contains 0s. Store it in a variable named `frequencies`. Use this array to count the number of times each word has appeared in the book. For example `frequencies[9]` should store how many times the word located in the index 9 of `V` (the sorted list) --which is the word "about"-- has been appreaed in the book (165 times). (10 points)


In [5]:
import numpy as np
# Your solution
frequencies = np.zeros(len(V))

for word in words:
    index = V.index(word)
    current_count = frequencies[index]
    frequencies[index] = current_count + 1
    
frequencies, frequencies[9] # Expected: array([ 1.,  1.,  1., ..., 11.,  1.,  1.]), 165.0

(array([ 1.,  1.,  1., ..., 11.,  1.,  1.]), 165.0)

Find the word that appeared most frequently in the book. Find the word itself as well as the number of times it was repeated in the book. Use numpy functions, i.e. do not iterate over the `frequencies` array manually using a `for` loop. (5 points)

In [6]:
# Your solution 
most_common_word_index = np.argmax(frequencies)
most_common_word = V[most_common_word_index]
max_frequency = int(frequencies[most_common_word_index])

print(f'"{most_common_word}" is the most common word which has appeared {max_frequency} times in the book.')
# Expected: "the" is the most common word which has appeared 3237 times in this book.

"the" is the most common word which has appeared 3237 times in the book.


Normalize all frequency values by dividing them by the maximum frequency value (using vectorized operators). After this the most common word in the book should get a normalized frequency of `1` and all other words get some value 
between `1/MAX` and `1`. (2.5 points)

In [12]:
# Your solution
print(frequencies)
normalized_frequencies = np.divide(frequencies, max_frequency)
normalized_frequencies

[ 1.  1.  1. ... 11.  1.  1.]


array([0.00030893, 0.00030893, 0.00030893, ..., 0.00339821, 0.00030893,
       0.00030893])

In [62]:
#print(tuple(zip(V, normalized_frequencies)))

We want to check if the normalized frequencies have any corelation to their ranks. If such correlation exists, the Zipf's law states that it is linear in a log-log space. Take the logarithm of normalized frequencies (as y values) and create a numpy array of the same size containing the rank of each word (as x values). For example if the frequencies array is `[0.1, 1, 0.01, 0.0001]` the x and y values will be `X = [2, 1, 3, 4] Y=[-1, 0, -2, -4]`. 

You might want to sort the normalized frequencies first to make the task easier. (2.5 points)

In [38]:
# Your solution
x = np.add(np.argsort(frequencies), 1)
y = np.log10(normalized_frequencies)
rank_matched = list(tuple(zip(x,y)))
print(rank_matched)



[(1, -3.5101426994025733), (2357, -3.5101426994025733), (2359, -3.5101426994025733), (2361, -3.5101426994025733), (2363, -3.5101426994025733), (2365, -0.4811649941937951), (2367, -2.254870194299267), (2370, -2.7319914490189294), (2371, -3.5101426994025733), (2372, -1.2926587551886668), (2373, -2.6650446593883164), (2378, -3.5101426994025733), (2379, -3.5101426994025733), (2381, -3.5101426994025733), (2382, -2.908082708074611), (2383, -3.5101426994025733), (2384, -3.5101426994025733), (2386, -3.5101426994025733), (2354, -3.209112703738592), (2387, -2.468750014244348), (2353, -3.5101426994025733), (2349, -3.209112703738592), (2322, -3.5101426994025733), (2325, -3.5101426994025733), (2326, -3.0330214446829107), (2328, -3.5101426994025733), (2331, -2.908082708074611), (2332, -2.5101426994025733), (2334, -3.5101426994025733), (2335, -3.5101426994025733), (2336, -2.231389098449744), (2337, -2.6650446593883164), (2338, -3.5101426994025733), (2339, -3.209112703738592), (2340, -2.66504465938831

In [33]:
test = np.array([0.1, 1, 0.01, 0.0001])
print(np.add(np.argsort(test), 1))
print(test)

[4 3 1 2]
[1.e-01 1.e+00 1.e-02 1.e-04]


Calculate the [pearson correlation coefficient](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient) on this data. The result is expected to be close to -1. Define appropriate functions for the the statistical calculations as neccessary. Additionally, you can use `pearsonr` function from `scipy` package to check if the calculated value is definitely correct. Though if you get a value close enough to -1 you can almost be sure that your implementation is correct and this step won't be necessary. (10 points)

In [ ]:
# Your solution goes here
def pcc(x, y):
    pass

pcc(x, y)

## Problem 2 - Log processing (50 points)

In this part of the assignment we are going to use regular expressions to mine data out of some webserver log files. Although these problems can be solved without use of RegExes, but for this assignment you need to use them.

A sample web server log file is provided along with this problem. In each line of the file one event is recorded. For simplicity all of the events in this file have the same format and are of the same type. Each event contains an ip address, date and time of the event, http method (`GET` or `POST`), a url, HTTP version, HTTP response code (usually 200), the response size in bytes, and the device's user agent which contains information about the device such as the brand and the operating system.

Since these logs have such a well defined format regular expressions are the prefect tool for breaking them down into parts and perform different analysis on them.

**Please make sure that when you are asked to write a function that _return_s something, you are _return_ing that value, not just _print_ing it**

We start off with a random log line and write python functions that use regular expressions to break it off to pieces.

In [39]:
import re

l = '5.106.145.204 - - [04/Sep/2019:13:51:39 +0430] "POST /v1/crash-report/incident/report/ HTTP/1.1" 200 65 "-" "Dalvik/1.6.0 (Linux; U; Android 4.2.2; GT-S7272 Build/JDQ39)"'
print(l)

5.106.145.204 - - [04/Sep/2019:13:51:39 +0430] "POST /v1/crash-report/incident/report/ HTTP/1.1" 200 65 "-" "Dalvik/1.6.0 (Linux; U; Android 4.2.2; GT-S7272 Build/JDQ39)"


Make a function that extracts the ip address part of the log line using regular expressions. (5 points)

In [44]:
def get_ip_address(l):
    ip = re.findall("(^\S+)", l)
    return ip


get_ip_address(l)  # Expected: '5.106.145.204'

['5.106.145.204']

Make a function that extracts the HTTP method, url, response code, and response size and returns a tuple. Use regular expressions. The http method is either `POST` or `GET` and the response code is always a 3 digit integer. (10 points)

In [61]:
def get_http_info(l):
    event = re.findall("\"(.+?) \"-\"", l)
    events = re.findall("(\S+)", event[0])
    http = events[0]
    url = events[1]
    reponse_code = events[3]
    response_size = events[4]
    return (http, url, int(reponse_code), int(response_size))

get_http_info(l)  # Expected: ('POST', '/v1/crash-report/incident/report/', 200, 65)
# Please note that the last two numbers are converted to integers

('POST', '/v1/crash-report/incident/report/', 200, 65)

Use regular expressions to break the date and time section apart and create a python datetime object based on that. Mind the time zone. convert the datetimes to MDT. Using `strptime` is a better solution in general, but for this assignment please stick to writing RegExes so you become more comfortable in writing and debugging them. (20 points)


In [ ]:
from datetime import datetime, timedelta, timezone
from calendar import month_abbr

MDT = timezone(timedelta(minutes=-6*60 + 0))

def get_datetime(l):
    # Your solution here
    return ...

get_datetime(l)  # Expected: datetime.datetime(2019, 9, 4, 3, 21, 39, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=64800)))

Read the log file line by line and use the `get_datetime` and `get_http_info` functions above to calculate the used bandwidth of the server (the sum of all the response sizes) per hour. Use a `dict` or a `defaultdict`. (15 points)

For example if there are 4 logs like:

    Sep 4 14:20 .... 65bytes
    Sep 4 14:35 .... 80bytes
    Sep 4 15:01 .... 44bytes
    Sep 5 18:20 .... 40bytes

The result will be like:

    Sep 4 14:00  145
    Sep 4 15:00  44
    Sep 5 18:00  40

In [ ]:
# Your solution here

# No specific format for the output is expected
# However the data will be something like:
#  2019, 7, 20 07:00    49130 bytes
#  2019, 7, 20 08:00    40469 bytes
#  2019, 7, 20 09:00    43556 bytes
#  2019, 7, 20 10:00    82526 bytes .... 